services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - support-ticket-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      retries: 5
      start_period: 10s

  api:
    image: asia-southeast2-docker.pkg.dev/dev-fairuz-agiza/backend-repo/backend-magnasight-fastapi:latest
    container_name: backend-magnasight
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      ADMIN_EMAIL: admin@dev.magnaglobal.id
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: support@dev.magnaglobal.id
      SMTP_PASS: oocdxcxzhmgcteqf
      GOOGLE_APPLICATION_CREDENTIALS: /gcp-sa.json
      # Firebase configuration from environment variables
      FIREBASE_SA_JSON: ${FIREBASE_SA_JSON:-}
      FIREBASE_TYPE: ${FIREBASE_TYPE:-service_account}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID:-dev-arfara-8244d}
      FIREBASE_PRIVATE_KEY_ID: ${FIREBASE_PRIVATE_KEY_ID:-}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY:-}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL:-}
      FIREBASE_CLIENT_ID: ${FIREBASE_CLIENT_ID:-}
      FIREBASE_AUTH_URI: ${FIREBASE_AUTH_URI:-https://accounts.google.com/o/oauth2/auth}
      FIREBASE_TOKEN_URI: ${FIREBASE_TOKEN_URI:-https://oauth2.googleapis.com/token}
      FIREBASE_CLIENT_X509_CERT_URL: ${FIREBASE_CLIENT_X509_CERT_URL:-}
    volumes:
      - ./gcp-sa.json:/gcp-sa.json
    networks:
      - support-ticket-network

networks:
  support-ticket-network:
    driver: bridge

volumes:
  postgres_data: