name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key user@VM_EXTERNAL_IP "
            cd /path/to/app &&
            git pull origin main &&
            docker-compose up -d --build
          "
