name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan ${{ vars.VM_EXTERNAL_IP }} >> ~/.ssh/known_hosts

      - name: Debug SSH Key
        run: |
          echo "SSH Private Key Length: $(wc -c < ~/.ssh/id_ed25519)"
          ls -lah ~/.ssh
          cat ~/.ssh/known_hosts

      - name: Execute deployment script via SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 root@${{ vars.VM_EXTERNAL_IP }} <<EOF
          cd backend-magnasight-fastapi
          git pull origin main
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          EOF


