name: Deploy FastAPI with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: dev-fairuz-agiza

      - name: Build and push Docker images
        run: |
          docker build -t gcr.io/dev-fairuz-agiza/backend-magnasight-fastapi:latest .
          docker tag gcr.io/dev-fairuz-agiza/backend-magnasight-fastapi:latest asia-southeast2-docker.pkg.dev/dev-fairuz-agiza/backend-magnasight-fastapi:${{ github.sha }}
          gcloud auth configure-docker
          docker push asia-southeast2-docker.pkg.dev/dev-fairuz-agiza/backend-magnasight-fastapi:latest
          docker push asia-southeast2-docker.pkg.dev/dev-fairuz-agiza/backend-magnasight-fastapi:${{ github.sha }}

      - name: Deploy to GCP VM using SSH
        run: |
          gcloud compute ssh root@backend-magnasight --zone=asia-southeast2-c --command="
            cd backend-magnasight-fastapi &&
            git pull origin main &&
            docker compose down &&
            docker compose pull &&
            docker compose up -d
          "
